name: CuSharp-Build

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish AOTC
        run: dotnet publish ./CuSharp.AOTC/CuSharp.AOTC.csproj -c Release --no-restore
      - uses: actions/upload-artifact@v3
        with:
          name: CuSharp.AOTC
          path: ./CuSharp.AOTC/bin/Release/**/publish/
